### PR TITLE
Update to use geoip2

### PR DESCRIPTION
**Pull request by ks3**
- use iso3166 module to lookup 3 character country codes (no longer in geoip data)
- telephone area code is no longer a field in geoip data

### CODE REVIEW

**Comment by adrianreber** [comment]
Thanks a lot! I just tried it on Fedora 31 with Python 3 and it does not run. Could you also look into porting it to Python 3?

**Comment by ks3** [comment]
Absolutely, I was planning to do a separate PR for that. I should be able to get something together in the next few days. 

-- kevin

**Comment by ks3** [comment]
The branch should now work with Python 3 on Fedora 31.

**Comment by adrianreber** [comment]
Thanks. that works now. There are small differences in the output:
```
$ curl http://127.0.0.1:8090/?ip=129.143.116.10 | jq -S
{
  "city": "Stuttgart",
  "country_code": "DE",
  "country_code3": "DEU",
  "country_name": "Germany",
  "dma_code": null,
  "ip": "129.143.116.10",
  "latitude": 48.7667,
  "longitude": 9.1833,
  "metro_code": null,
  "postal_code": "70173",
  "region": "BW",
  "region_name": "Baden-Württemberg Region",
  "time_zone": "Europe/Berlin"
}
$ curl https://geoip.fedoraproject.org/city?ip=129.143.116.10 | jq -S
{
  "area_code": 0,
  "city": "Stuttgart",
  "country_code": "DE",
  "country_code3": "DEU",
  "country_name": "Germany",
  "dma_code": 0,
  "ip": "129.143.116.10",
  "latitude": 48.766700744628906,
  "longitude": 9.183300018310547,
  "metro_code": 0,
  "postal_code": "70173",
  "region": "01",
  "region_name": "Baden-Wurttemberg",
  "time_zone": "Europe/Berlin"
}
```
The new output is missing `area_code`, `dma_code`  and `metro_code` have different output. `region` changed to a string and the region code includes correctly a `ü` instead of a `u`.

@nirik can we get input from someone using this data to verify that these changes are not a problem? Besides that it looks good.

**Comment by M4rtinK** [comment]
Anaconda geolocation [uses](https://github.com/rhinstaller/anaconda/blob/master/pyanaconda/geoloc.py#L482) just `country_code` and `timezone`. As those two look the same, all should be fine from the installer perspective.

**Comment by adrianreber** [comment]
I would say this can be merged. I cannot merge it, however.

**Comment by cverna** [comment]
Merging then :) thanks @ks3 and @adrianreber

**Pull request merged**
